import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

const translations = {
  es: {
    'Dashboard': 'Panel',
    'Clientes': 'Clientes',
    'Servicios': 'Servicios',
    'Soporte': 'Soporte',
    'Configuración': 'Configuración',
    'Buscar...': 'Buscar...',
    'Crear Cliente': 'Crear Cliente',
    'Crear Servicio': 'Crear Servicio',
    'Crear Ticket': 'Crear Ticket',
    'Clientes Activos': 'Clientes Activos',
    'Tickets Abiertos': 'Tickets Abiertos',
    'Servicios Totales': 'Servicios Totales',
    'Ingresos del Mes': 'Ingresos del Mes',
    'Actividad Reciente': 'Actividad Reciente',
    'Acciones Rápidas': 'Acciones Rápidas',
    'Ver Todos': 'Ver Todos',
    'Empresa': 'Empresa',
    'RFC': 'RFC',
    'Estado': 'Estado',
    'Servicios': 'Servicios',
    'Creado': 'Creado',
    'Acciones': 'Acciones',
    'Activo': 'Activo',
    'Inactivo': 'Inactivo',
    'Editar': 'Editar',
    'Eliminar': 'Eliminar',
    'Ver': 'Ver',
    'Nombre': 'Nombre',
    'Categoría': 'Categoría',
    'Precio': 'Precio',
    'Ciclo': 'Ciclo',
    'Descripción': 'Descripción',
    'Título': 'Título',
    'Cliente': 'Cliente',
    'Prioridad': 'Prioridad',
    'Baja': 'Baja',
    'Media': 'Media',
    'Alta': 'Alta',
    'Urgente': 'Urgente',
    'Abierto': 'Abierto',
    'En Progreso': 'En Progreso',
    'Resuelto': 'Resuelto',
    'Cerrado': 'Cerrado',
    'No se encontraron clientes': 'No se encontraron clientes',
    'Agrega tu primer cliente para comenzar': 'Agrega tu primer cliente para comenzar',
    'No hay servicios disponibles': 'No hay servicios disponibles',
    'Crea tu primer servicio para comenzar': 'Crea tu primer servicio para comenzar',
    'No hay tickets de soporte': 'No hay tickets de soporte',
    'Los tickets aparecerán aquí cuando los clientes necesiten ayuda': 'Los tickets aparecerán aquí cuando los clientes necesiten ayuda',
    'Error al cargar datos': 'Error al cargar datos',
    'Reintentar': 'Reintentar',
    'Página no encontrada': 'Página no encontrada',
    'La página que buscas no existe': 'La página que buscas no existe',
    'Volver al Panel': 'Volver al Panel',
    'Configuración del Sistema': 'Configuración del Sistema',
    'Configuración General': 'Configuración General',
    'Configuración de Idioma': 'Configuración de Idioma',
    'Idioma de la interfaz': 'Idioma de la interfaz',
    'Cambia el idioma de la aplicación': 'Cambia el idioma de la aplicación',
    'Cambiar idioma': 'Cambiar idioma',
    'Español': 'Español',
    'Inglés': 'Inglés',
    'Moneda': 'Moneda',
    'Moneda utilizada en la aplicación': 'Moneda utilizada en la aplicación',
    'Peso Mexicano': 'Peso Mexicano',
    'Tema de la interfaz': 'Tema de la interfaz',
    'Cambia entre modo claro y oscuro': 'Cambia entre modo claro y oscuro',
    'Cambiar tema': 'Cambiar tema',
    'Claro': 'Claro',
    'Oscuro': 'Oscuro',
    'Mi perfil': 'Mi perfil',
    'Mi Perfil': 'Mi Perfil',
    'Nombre completo': 'Nombre completo',
    'Ingresa tu nombre completo': 'Ingresa tu nombre completo',
    'Correo electrónico': 'Correo electrónico',
    'correo@ejemplo.com': 'correo@ejemplo.com',
    'Teléfono': 'Teléfono',
    'Número de teléfono': 'Número de teléfono',
    'Nombre de la empresa': 'Nombre de la empresa',
    'Cargo': 'Cargo',
    'Tu cargo o posición': 'Tu cargo o posición',
    'Cancelar': 'Cancelar',
    'Guardar': 'Guardar',
    'Error al cargar perfil': 'Error al cargar perfil',
    'Perfil actualizado correctamente': 'Perfil actualizado correctamente',
    'Error al actualizar perfil': 'Error al actualizar perfil',
'Notificaciones': 'Notificaciones',
    'Recibir notificaciones por email': 'Recibir notificaciones por email',
    'Configuración de Módulos': 'Configuración de Módulos',
    'Guardar Cambios': 'Guardar Cambios',
    'Cambios guardados correctamente': 'Cambios guardados correctamente',
    'Equipo': 'Equipo',
    'Gestión de Equipo': 'Gestión de Equipo',
    'Administra los usuarios y sus permisos en el sistema': 'Administra los usuarios y sus permisos en el sistema',
    'Agregar Usuario': 'Agregar Usuario',
    'Buscar por nombre o email...': 'Buscar por nombre o email...',
    'Todos los roles': 'Todos los roles',
    'Todos los estados': 'Todos los estados',
    'No hay usuarios en el equipo': 'No hay usuarios en el equipo',
    'Agrega el primer usuario para comenzar': 'Agrega el primer usuario para comenzar',
    'Crear Usuario': 'Crear Usuario',
    'Editar Usuario': 'Editar Usuario',
    'Usuario creado correctamente': 'Usuario creado correctamente',
    'Usuario actualizado correctamente': 'Usuario actualizado correctamente',
    'Usuario eliminado correctamente': 'Usuario eliminado correctamente',
    '¿Estás seguro de que deseas eliminar este usuario?': '¿Estás seguro de que deseas eliminar este usuario?',
    'Creando...': 'Creando...',
    'Guardando...': 'Guardando...',
    'Rol': 'Rol',
    'Superadmin': 'Superadmin',
    'Admin': 'Admin',
    'Colaborator': 'Colaborator'
  },
  en: {
    'Dashboard': 'Dashboard',
    'Clientes': 'Clients',
    'Servicios': 'Services',
    'Soporte': 'Support',
    'Configuración': 'Settings',
    'Buscar...': 'Search...',
    'Crear Cliente': 'Create Client',
    'Crear Servicio': 'Create Service',
    'Crear Ticket': 'Create Ticket',
    'Clientes Activos': 'Active Clients',
    'Tickets Abiertos': 'Open Tickets',
    'Servicios Totales': 'Total Services',
    'Ingresos del Mes': 'Monthly Revenue',
    'Actividad Reciente': 'Recent Activity',
    'Acciones Rápidas': 'Quick Actions',
    'Ver Todos': 'View All',
    'Empresa': 'Company',
    'RFC': 'RFC',
    'Estado': 'Status',
    'Servicios': 'Services',
    'Creado': 'Created',
    'Acciones': 'Actions',
    'Activo': 'Active',
    'Inactivo': 'Inactive',
    'Editar': 'Edit',
    'Eliminar': 'Delete',
    'Ver': 'View',
    'Nombre': 'Name',
    'Categoría': 'Category',
    'Precio': 'Price',
    'Ciclo': 'Cycle',
    'Descripción': 'Description',
    'Título': 'Title',
    'Cliente': 'Client',
    'Prioridad': 'Priority',
    'Baja': 'Low',
    'Media': 'Medium',
    'Alta': 'High',
    'Urgente': 'Urgent',
    'Abierto': 'Open',
    'En Progreso': 'In Progress',
    'Resuelto': 'Resolved',
    'Cerrado': 'Closed',
    'No se encontraron clientes': 'No clients found',
    'Agrega tu primer cliente para comenzar': 'Add your first client to get started',
    'No hay servicios disponibles': 'No services available',
    'Crea tu primer servicio para comenzar': 'Create your first service to get started',
    'No hay tickets de soporte': 'No support tickets',
    'Los tickets aparecerán aquí cuando los clientes necesiten ayuda': 'Tickets will appear here when clients need help',
    'Error al cargar datos': 'Failed to load data',
    'Reintentar': 'Retry',
    'Página no encontrada': 'Page not found',
    'La página que buscas no existe': 'The page you are looking for does not exist',
    'Volver al Panel': 'Back to Dashboard',
    'Configuración del Sistema': 'System Settings',
    'Configuración General': 'General Settings',
    'Configuración de Idioma': 'Language Settings',
    'Idioma de la interfaz': 'Interface Language',
    'Cambia el idioma de la aplicación': 'Change the application language',
    'Cambiar idioma': 'Change Language',
    'Español': 'Spanish',
    'Inglés': 'English',
    'Moneda': 'Currency',
    'Moneda utilizada en la aplicación': 'Currency used in the application',
    'Peso Mexicano': 'Mexican Peso',
    'Tema de la interfaz': 'Interface Theme',
    'Cambia entre modo claro y oscuro': 'Switch between light and dark mode',
    'Cambiar tema': 'Change Theme',
    'Claro': 'Light',
    'Oscuro': 'Dark',
    'Mi perfil': 'My Profile',
    'Mi Perfil': 'My Profile',
    'Nombre completo': 'Full Name',
    'Ingresa tu nombre completo': 'Enter your full name',
    'Correo electrónico': 'Email Address',
    'correo@ejemplo.com': 'email@example.com',
    'Teléfono': 'Phone',
    'Número de teléfono': 'Phone number',
    'Nombre de la empresa': 'Company name',
    'Cargo': 'Position',
    'Tu cargo o posición': 'Your position or role',
    'Cancelar': 'Cancel',
    'Guardar': 'Save',
    'Error al cargar perfil': 'Error loading profile',
    'Perfil actualizado correctamente': 'Profile updated successfully',
    'Error al actualizar perfil': 'Error updating profile',
    'Notificaciones': 'Notifications',
'Recibir notificaciones por email': 'Receive email notifications',
    'Notificaciones push': 'Push notifications',
    'Configuración de Módulos': 'Module Settings',
    'Guardar Cambios': 'Save Changes',
    'Cambios guardados correctamente': 'Changes saved successfully',
    'Equipo': 'Team',
    'Gestión de Equipo': 'Team Management',
    'Administra los usuarios y sus permisos en el sistema': 'Manage users and their permissions in the system',
    'Agregar Usuario': 'Add User',
    'Buscar por nombre o email...': 'Search by name or email...',
    'Todos los roles': 'All roles',
    'Todos los estados': 'All statuses',
    'No hay usuarios en el equipo': 'No team members found',
    'Agrega el primer usuario para comenzar': 'Add the first user to get started',
    'Crear Usuario': 'Create User',
    'Editar Usuario': 'Edit User',
    'Usuario creado correctamente': 'User created successfully',
    'Usuario actualizado correctamente': 'User updated successfully',
    'Usuario eliminado correctamente': 'User deleted successfully',
    '¿Estás seguro de que deseas eliminar este usuario?': 'Are you sure you want to delete this user?',
    'Creando...': 'Creating...',
    'Guardando...': 'Saving...',
    'Rol': 'Role',
    'Superadmin': 'Superadmin',
    'Admin': 'Admin',
    'Colaborator': 'Collaborator'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('es');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'es' ? 'en' : 'es');
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};